/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const CartProduct = IDL.Record({
  'quantity' : IDL.Nat,
  'product' : Product,
});
export const Cart = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(CartProduct),
});
export const BakeryOrder = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'cart' : Cart,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getMenu' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(BakeryOrder)], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const CartProduct = IDL.Record({ 'quantity' : IDL.Nat, 'product' : Product });
  const Cart = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(CartProduct),
  });
  const BakeryOrder = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'cart' : Cart,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getMenu' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(BakeryOrder)], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };