/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BakeryOrder {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'cart' : Cart,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export interface Cart { 'total' : bigint, 'items' : Array<CartProduct> }
export interface CartProduct { 'quantity' : bigint, 'product' : Product }
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface _SERVICE {
  'getMenu' : ActorMethod<[], Array<Product>>,
  'getOrders' : ActorMethod<[], Array<BakeryOrder>>,
  'placeOrder' : ActorMethod<
    [string, string, string, string, Array<[bigint, bigint]>],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];